### ISSUE TITLE
Project import but I can't edit it.

### ISSUE THREAD

**Issue by carcagi** [toger5/OpenCardGame#1]
First of all thanks for sharing this, I am learning Godot and I like to learn from other people projects. :)
In Godot 3.0.5.stable.official.6a88e22 I can import the project, but the edit action fails.
And when I try to rename it, it shows the error:
"Couldn't load project.godot in project path (error 12). It may be missing or corrupted."
Should I be using a different Godot Version?

**Comment by carcagi** [comment]
I will answer myself, and if someone else has the same problem.
Edit project.godot and change config_version=4 to config_version=3

**Comment by toger5** [comment]
@carcagi
Thank you! For showing interest!
Yea the project is developed with current master. It also needs the features from current master to do the card rendering in a different viewport.
Maybe you should get a nightly build for it?

Keep in mind, that this is really WIP. It still might have some interesting approaches. You could check how the cards are created. For performance reasons they are just bitmaps. And are only updated when needed. (Using godots amasing vieport system) also there is extensive tween usage which might be interesting.
But Don't take the overall structure as insparation 😬 some things are just hacked together for now.

**Comment by toger5** [comment]
Also apologies for the cards, pictures + text. I tried to be funny. Although i now think it makes me look like a weirdo 😝

**Comment by carcagi** [comment]
I just download the nightly build, and yes, it now works :). 
Don't worry about the pictures, they are funny ( and weird ). 

Keep up the good work. I am always willing to learn and I have learned a lot from this project.

Thanks.
